### ISSUE TITLE
Joplin_Complete_Link V0.1 looks like a completely different plugin than described

### ISSUE THREAD

**Issue by franciskcso** [S73ph4n/joplin_complete_link#1]
I was browsing Joplin_Complete_Link and the initial README.md file shows a plugin which auto completes a link. However, after installing it, the plugin looks like it does something completely different. I'm wondering if it another plugin was accidentally compiled? Joplin_Complete_Link V0.1 as it is uploaded, looks as if it is designed to send a highlighted selection into another note with these 4 icons which do not relate to the original README.md file.

![image](https://user-images.githubusercontent.com/6107137/143507474-3d6d6d92-409f-4ef8-a5f0-d4412e226902.png)

**Comment by Saturo78** [comment]
Yes, the downloaded file is definitely an other plugin than the mentioned one.
Could you please fix the path?

**Comment by S73ph4n** [comment]
It turns out some files got mixed. 
It is fixed in V1.0.1.
